### PR TITLE
async loadDocument

### PR DESCRIPTION
**Pull request by create3000**

### CODE REVIEW

**Comment by andreasplesch** [comment]
Thanks, I tested this in the alpha branch. It looks good but I want to apply the PR to the master branch only after x_ite gets a new 'latest' tag because all tests use 'latest' x_ite.

**Comment by create3000** [comment]
This will soon be possible. I will release a new version on Sunday this week.

**Comment by create3000** [comment]
New version 4.4.4 is out now and can be tested.

**Comment by andreasplesch** [comment]
Thanks.

**Pull request merged**
